spring.application.name=TREEdu
server.port=${PORT:3001}
api.base-url=${API_BASE_URL:http://localhost:3001/api}

server.forward-headers-strategy=framework
logging.level.vn.hcmute.edu.materialsservice=DEBUG

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/materials_db}
spring.data.mongodb.auto-index-creation=true

# Disable JPA
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


# Redis
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}

# Session
spring.session.store-type=mongodb
spring.session.mongodb.collection-name=sessions

# API Keys
gemini.api.key=${GEMINI_API_KEY}
fpt.api-key=${FPT_API_KEY}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Mail
#spring.mail.host=${SPRING_MAIL_HOST}
#spring.mail.port=${SPRING_MAIL_PORT}
#spring.mail.username=${SPRING_MAIL_USERNAME}
#spring.mail.password=${SPRING_MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.test-connection=false
#spring.mail.default-encoding=UTF-8

# Resend Email API
resend.api.key=${RESEND_API_KEY}
resend.from.email=${RESEND_FROM_EMAIL:TREEdu <onboarding@resend.dev>}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
app.upload.dir=uploads/audio/
app.base-url=${FRONTEND_URL:http://localhost:3000}

# AI Service
ai.service.url=${AI_SERVICE_URL:http://localhost:8000/ai/v1/transcribe}

# Cloudinary
cloudinary.url=${CLOUDINARY_URL}
cloudinary.avatar-folder=avatars
